markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "Shuangman Wu"
markdown: rdiscount

author: "wsm"
baseurl: /blog/
disqus: "gopherwood"

navigations:
  - title: Home
    class: fa fa-home
    href: /index.html
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: Categories
    class: fa fa-sort-amount-desc
    href: /categories.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://www.baidu.com
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

