markdown: rdiscount
highlighter: pygments
permalink: /blog/:year/:month/:day/:title.html
name: "Shuangman Wu"
markdown: rdiscount

author: "wsm"
baseurl: 
disqus: "gopherwood"

navigations:
  - title: Home
    class: fa fa-home
    href: /blog/index.html
  - title: Archive
    class: fa fa-list-ul
    href: /blog/archive.html
  - title: Tags
    class: fa fa-tags
    href: /blog/tags.html
  - title: Categories
    class: fa fa-sort-amount-desc
    href: /blog/categories.html
  - title: About
    class: fa fa-user
    href: /blog/about.html
  - title: Gallery
    class: fa fa-film
    href: http://www.baidu.com
  - title: Subscribe
    class: fa fa-rss
    href: /blog/atom.xml

